- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]

    - name: Display shell output
      shell: aws sts get-caller-identity

